name: Train and Release ML Model

on:
  push:
    paths:
      - 'MLProject/modelling.py'
      - 'MLProject/crop_data_cleaned.csv'
  workflow_dispatch:

env:
  DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/msml-crop-mlflow:latest
  DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_USER_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  train-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas xgboost scikit-learn mlflow matplotlib seaborn dotenv dagshub

      - name: Run training script
        working-directory: MLProject
        run: |
          python modelling.py

      - name: Archive model artifact
        uses: actions/upload-artifact@v4
        with:
          name: mlflow_model
          path: MLProject/artifacts/mlflow_model

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: 'v1.0.0'
          name: 'ML Model Release'
          files: MLProject/artifacts/mlflow_model/**

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build MLflow model Docker image
        working-directory: MLProject
        run: |
          mlflow models build-docker -m artifacts/mlflow_model -n msml-crop-mlflow

      - name: Push Docker image to DockerHub
        run: |
          docker tag msml-crop-mlflow:latest $DOCKER_IMAGE
          docker push $DOCKER_IMAGE